/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainAPP.GUI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Vincent
 */
public class Login_STUDENT_FRAME extends javax.swing.JFrame {

    /**
     * Creates new form Login_ADMIN_FRAME
     */
    public Login_STUDENT_FRAME() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        student_login_id = new javax.swing.JTextField();
        student_login_password = new javax.swing.JPasswordField();
        home_button_login = new javax.swing.JButton();
        student_login_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        student_login_id.setBackground(new java.awt.Color(0,0,0,0));
        student_login_id.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        student_login_id.setForeground(new java.awt.Color(255, 255, 255));
        student_login_id.setText("STUDENT ID");
        student_login_id.setToolTipText("");
        student_login_id.setBorder(null);
        student_login_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                student_login_idFocusGained(evt);
            }
        });
        student_login_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_login_idActionPerformed(evt);
            }
        });
        getContentPane().add(student_login_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 200, 50));

        student_login_password.setBackground(new java.awt.Color(0,0,0,0));
        student_login_password.setForeground(new java.awt.Color(255, 255, 255));
        student_login_password.setText("jPasswordField1");
        student_login_password.setBorder(null);
        student_login_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                student_login_passwordFocusGained(evt);
            }
        });
        getContentPane().add(student_login_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 200, 40));

        home_button_login.setOpaque(false);
        home_button_login.setContentAreaFilled(false); //to make the content area transparent
        home_button_login.setBorderPainted(false); //to make the borders transparent
        home_button_login.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        home_button_login.setForeground(new java.awt.Color(51, 108, 251));
        home_button_login.setBorder(null);
        home_button_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_button_login.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        home_button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_button_loginActionPerformed(evt);
            }
        });
        getContentPane().add(home_button_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 385, 220, 30));

        student_login_btn.setOpaque(false);
        student_login_btn.setContentAreaFilled(false); //to make the content area transparent
        student_login_btn.setBorderPainted(false); //to make the borders transparent
        student_login_btn.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        student_login_btn.setForeground(new java.awt.Color(51, 108, 251));
        student_login_btn.setBorder(null);
        student_login_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        student_login_btn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        student_login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_login_btnActionPerformed(evt);
            }
        });
        getContentPane().add(student_login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 220, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainAPP/assets/LOGIN-PAGE-STUDENT.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTextField2.requestFocusInWindow();
        jTextField2.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        jTextField2.setText("ADMIN ID");
        jTextField2.setBorder(null);
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 200, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void student_login_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_login_idActionPerformed
        student_login_id.setFocusable(true);
    }//GEN-LAST:event_student_login_idActionPerformed

    private void student_login_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_student_login_idFocusGained
        student_login_id.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_student_login_idFocusGained

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        jTextField2.requestFocusInWindow();
    }//GEN-LAST:event_formWindowActivated

    private void student_login_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_student_login_passwordFocusGained
        student_login_password.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_student_login_passwordFocusGained

    private void home_button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_button_loginActionPerformed
        Login_STUDENT_FRAME.this.setVisible(false);
        new Login_FRAME().setVisible(true);
    }//GEN-LAST:event_home_button_loginActionPerformed

    private void student_login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_login_btnActionPerformed
    Connection con = null;
    try {
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver"); //Driver name
        con = DriverManager.getConnection("jdbc:derby://localhost:1527/CLINIC_FinalProject", "clinicadmin", "clinicadmin");
        String id = student_login_id.getText();
        String pwd = student_login_password.getText();

        // Check if the ID exists
        String checkIdSql = "SELECT * FROM STUDENTCREDENTIALS WHERE student_no = ?";
        try (PreparedStatement idStmt = con.prepareStatement(checkIdSql)) {
            idStmt.setString(1, id);
            try (ResultSet idRs = idStmt.executeQuery()) {
                if (idRs.next()) {
                    // ID exists, now validate the password
                    String validatePwdSql = "SELECT * FROM STUDENTCREDENTIALS WHERE student_no = ? AND student_pwd = ?";
                    try (PreparedStatement pwdStmt = con.prepareStatement(validatePwdSql)) {
                        pwdStmt.setString(1, id);
                        pwdStmt.setString(2, pwd);
                        try (ResultSet pwdRs = pwdStmt.executeQuery()) {
                            if (pwdRs.next()) {
                                String sql = "SELECT " +
                                    "ds.student_no, " +
                                    "ds.lastname AS student_lastname, " +
                                    "ds.firstname AS student_firstname, " +
                                    "ds.email, " +
                                    "ds.address, " +
                                    "ds.bday, " +
                                    "ds.cp_num, " +  
                                    "ds.status, " +
                                    "ds.gender AS student_gender, " +
                                    "ds.course_code, " +
                                    "dc.description AS course_description, " +
                                    "dc.college_code, " +
                                    "dtc.description AS college_description, " +
                                    "fc.semester, " +
                                    "fc.illness_code, " +
                                    "di.description AS illness_description, " +
                                    "fc.attending_physician_id, " +
                                    "de_attending.firstname || ' ' || de_attending.lastname AS attending_physician_fullname, " +
                                    "fc.prepared_by_id, " +
                                    "de_prepared.firstname || ' ' || de_prepared.lastname AS prepared_by_fullname, " +
                                    "fc.date_consulted, " +
                                    "fc.diagnosis " +
                                "FROM " +
                                    "DT_STUDENT ds " +
                                "JOIN DT_COURSE dc ON ds.course_code = dc.course_code " +
                                "JOIN DT_COLLEGE dtc ON dc.college_code = dtc.college_code " +
                                "JOIN FT_CONSULTATION fc ON ds.student_no = fc.student_no " +
                                "JOIN DT_ILLNESS di ON fc.illness_code = di.illness_code " +
                                "LEFT JOIN DT_EMPLOYEE de_attending ON fc.attending_physician_id = de_attending.employee_id " +
                                "LEFT JOIN DT_EMPLOYEE de_prepared ON fc.prepared_by_id = de_prepared.employee_id " +
                                "WHERE " +
                                    "ds.student_no = ? AND ds.status = 'A'";


                                    try (PreparedStatement pstmt = con.prepareStatement(sql)) {
                                        pstmt.setString(1, id);
                                        try (ResultSet rs = pstmt.executeQuery()) {
                                            if (rs.next()) {
                                                // Retrieve information from the result set
                                                String student_no = rs.getString("student_no");
                                                String firstName = rs.getString("student_firstname");
                                                String lastName = rs.getString("student_lastname");
                                                String email = rs.getString("email");
                                                String address = rs.getString("address");
                                                String bday = rs.getString("bday");
                                                String status = rs.getString("status");
                                                String cp_num = rs.getString("cp_num");
                                                String gender = rs.getString("student_gender");
                                                String courseDescription = rs.getString("course_description");
                                                String collegeDescription = rs.getString("college_description");
                                                String illnessDescription = rs.getString("illness_description");
                                                String attendingPhysician = rs.getString("attending_physician_fullname");
                                                String preparedBy = rs.getString("prepared_by_fullname");
                                                String dateConsulted = rs.getString("date_consulted");
                                                String diagnosis = rs.getString("diagnosis");

                                                // Open the Show Information Frame and display the retrieved information
                                                Main_STUDENT_FRAME showInfoFrame = new Main_STUDENT_FRAME(student_no, firstName, lastName, email, address, bday, cp_num, gender, status, courseDescription, collegeDescription, illnessDescription, attendingPhysician, preparedBy, dateConsulted, diagnosis);
                                                showInfoFrame.setVisible(true);
                                                dispose();
                                            } else {
                                                JOptionPane.showMessageDialog(this, "No student information found for ID: " + id, "", JOptionPane.WARNING_MESSAGE);
                                            }
                                        }
                                    }
                            } else {
                                JOptionPane.showMessageDialog(this, "Invalid Password!", "", JOptionPane.WARNING_MESSAGE);
                            }
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Student ID does not exist!", "", JOptionPane.WARNING_MESSAGE);
                }
            }
        }

    } catch (Exception e) {
        System.out.println(e.getMessage());
    } finally {
        try {
            if (con != null) {
                con.close();
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    }//GEN-LAST:event_student_login_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_STUDENT_FRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_STUDENT_FRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_STUDENT_FRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_STUDENT_FRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_STUDENT_FRAME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton home_button_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton student_login_btn;
    private javax.swing.JTextField student_login_id;
    private javax.swing.JPasswordField student_login_password;
    // End of variables declaration//GEN-END:variables


}
