package MainAPP.GUI;

import java.awt.Color;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vincent
 */
public class Login_FRAME extends javax.swing.JFrame {

    ImageIcon ii;
    
    /**
     * Creates new form Login_FRAME
     */
    public Login_FRAME() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcome_user_lbl = new javax.swing.JLabel();
        admin_login_panel = new javax.swing.JPanel();
        admin_icon_label = new javax.swing.JLabel();
        login_as_label1 = new javax.swing.JLabel();
        admin_login_label = new javax.swing.JLabel();
        patient_login_panel = new javax.swing.JPanel();
        login_as_label2 = new javax.swing.JLabel();
        patient_icon_label = new javax.swing.JLabel();
        patient_login_label = new javax.swing.JLabel();
        employee_login = new javax.swing.JPanel();
        login_as_label3 = new javax.swing.JLabel();
        employee_icon_label = new javax.swing.JLabel();
        employee_login_label = new javax.swing.JLabel();
        BG_LOGIN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome_user_lbl.setFont(new java.awt.Font("Lato", 0, 40)); // NOI18N
        welcome_user_lbl.setForeground(new java.awt.Color(37, 40, 43));
        welcome_user_lbl.setText("Welcome, User !");
        getContentPane().add(welcome_user_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));

        admin_login_panel.setBackground(new java.awt.Color(0,0,0,0));
        admin_login_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin_login_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin_login_panelMouseClicked(evt);
            }
        });

        admin_icon_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainAPP/assets/admin_icon.png"))); // NOI18N

        login_as_label1.setFont(new java.awt.Font("Lato", 0, 19)); // NOI18N
        login_as_label1.setText("Login as");

        admin_login_label.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        admin_login_label.setForeground(new java.awt.Color(51, 108, 251));
        admin_login_label.setText("ADMIN");

        javax.swing.GroupLayout admin_login_panelLayout = new javax.swing.GroupLayout(admin_login_panel);
        admin_login_panel.setLayout(admin_login_panelLayout);
        admin_login_panelLayout.setHorizontalGroup(
            admin_login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_login_panelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(admin_icon_label)
                .addGap(34, 34, 34)
                .addGroup(admin_login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(login_as_label1)
                    .addComponent(admin_login_label))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        admin_login_panelLayout.setVerticalGroup(
            admin_login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin_login_panelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(admin_login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(admin_login_panelLayout.createSequentialGroup()
                        .addComponent(login_as_label1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(admin_login_label))
                    .addComponent(admin_icon_label))
                .addGap(24, 24, 24))
        );

        getContentPane().add(admin_login_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 230, -1));

        patient_login_panel.setBackground(new java.awt.Color(0,0,0,0));
        patient_login_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        patient_login_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patient_login_panelMouseClicked(evt);
            }
        });

        login_as_label2.setFont(new java.awt.Font("Lato", 0, 19)); // NOI18N
        login_as_label2.setText("Login as");

        patient_icon_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainAPP/assets/patient_icon.png"))); // NOI18N

        patient_login_label.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        patient_login_label.setForeground(new java.awt.Color(51, 108, 251));
        patient_login_label.setText("STUDENT");

        javax.swing.GroupLayout patient_login_panelLayout = new javax.swing.GroupLayout(patient_login_panel);
        patient_login_panel.setLayout(patient_login_panelLayout);
        patient_login_panelLayout.setHorizontalGroup(
            patient_login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patient_login_panelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(patient_icon_label)
                .addGap(34, 34, 34)
                .addGroup(patient_login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(login_as_label2)
                    .addComponent(patient_login_label))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        patient_login_panelLayout.setVerticalGroup(
            patient_login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patient_login_panelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(patient_login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(patient_login_panelLayout.createSequentialGroup()
                        .addComponent(login_as_label2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patient_login_label))
                    .addComponent(patient_icon_label))
                .addGap(24, 24, 24))
        );

        getContentPane().add(patient_login_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 260, -1));

        employee_login.setBackground(new java.awt.Color(0,0,0,0));
        employee_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employee_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employee_loginMouseClicked(evt);
            }
        });

        login_as_label3.setFont(new java.awt.Font("Lato", 0, 19)); // NOI18N
        login_as_label3.setText("Login as");

        employee_icon_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainAPP/assets/employee_icon.png"))); // NOI18N

        employee_login_label.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        employee_login_label.setForeground(new java.awt.Color(51, 108, 251));
        employee_login_label.setText("EMPLOYEE");

        javax.swing.GroupLayout employee_loginLayout = new javax.swing.GroupLayout(employee_login);
        employee_login.setLayout(employee_loginLayout);
        employee_loginLayout.setHorizontalGroup(
            employee_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employee_loginLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(employee_icon_label)
                .addGap(34, 34, 34)
                .addGroup(employee_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(login_as_label3)
                    .addComponent(employee_login_label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        employee_loginLayout.setVerticalGroup(
            employee_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employee_loginLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(employee_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(employee_loginLayout.createSequentialGroup()
                        .addComponent(login_as_label3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(employee_login_label))
                    .addComponent(employee_icon_label))
                .addGap(24, 24, 24))
        );

        getContentPane().add(employee_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 280, 100));

        BG_LOGIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainAPP/assets/LOGIN-PAGE.png"))); // NOI18N
        getContentPane().add(BG_LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admin_login_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_login_panelMouseClicked
        Login_FRAME.this.setVisible(false);
        new Login_ADMIN_FRAME().setVisible(true);
    }//GEN-LAST:event_admin_login_panelMouseClicked

    private void patient_login_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patient_login_panelMouseClicked
        Login_FRAME.this.setVisible(false);
        new Login_STUDENT_FRAME().setVisible(true);
    }//GEN-LAST:event_patient_login_panelMouseClicked

    private void employee_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employee_loginMouseClicked
        Login_FRAME.this.setVisible(false);
        new Login_EMPLOYEE_FRAME().setVisible(true);
    }//GEN-LAST:event_employee_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_FRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_FRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_FRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_FRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_FRAME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_LOGIN;
    private javax.swing.JLabel admin_icon_label;
    private javax.swing.JLabel admin_login_label;
    private javax.swing.JPanel admin_login_panel;
    private javax.swing.JLabel employee_icon_label;
    private javax.swing.JPanel employee_login;
    private javax.swing.JLabel employee_login_label;
    private javax.swing.JLabel login_as_label1;
    private javax.swing.JLabel login_as_label2;
    private javax.swing.JLabel login_as_label3;
    private javax.swing.JLabel patient_icon_label;
    private javax.swing.JLabel patient_login_label;
    private javax.swing.JPanel patient_login_panel;
    private javax.swing.JLabel welcome_user_lbl;
    // End of variables declaration//GEN-END:variables
}
